CREATE TABLE product (
prodnumber INTEGER PRIMARY KEY,
prodname VARCHAR(100) NOT NULL,
price DECIMAL(10,2),
cost DECIMAL(10,2),
prodcategory VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;